### PR TITLE
GeoPandas 1.0.0 rc1

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@conda-forge-admin, please rerender

**Comment by jorisvandenbossche** [comment]
@conda-forge-admin, please rerender

**Comment by jorisvandenbossche** [comment]
https://github.com/conda-forge/geopandas-feedstock/pull/114/commits/773ac56e9b1525899666fd3e95a84c49ae5d58b2 is the commit with the relevant changes to look at

**Review by martinfleis — APPROVED** [review]
Thanks!

**Comment by jorisvandenbossche** [comment]
Confirmed that `mamba create -n test-geopandas-rc python=3.11 geopandas --channel conda-forge/label/geopandas_dev --channel conda-forge` works

**Pull request merged**
