### PR TITLE
minimum requirement of pandas 0.23

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@conda-forge-admin, please rerender

**Comment by jorisvandenbossche** [comment]
@conda-forge-admin, please rerender

**Comment by jorisvandenbossche** [comment]
@ocefpaf would there be any reason that there is a problem with rerendering?

**Comment by ocefpaf** [comment]
The heroku service is a little bit flaky lately. I checked locally and no re-render is needed here. The feedstock is up to date. This is good to merge!

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
