### PR TITLE
add license

### PR DESCRIPTION
**Pull request by ocefpaf**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Is it now best practice to include a copy of the license here instead of linking to license in package repo? (so if license is changed (eg year range), needs to update here as well)

**Comment by ocefpaf** [comment]
> Is it now best practice to include a copy of the license here instead of linking to license in package repo? (so if license is changed (eg year range), needs to update here as well)

Actually the best practice is to have the license in the source tarball :smile: 

I'm planning to send a PR upstream later to add it to the `MANIFEST.in` file to ensure it is there.

**Comment by jorisvandenbossche** [comment]
Ah, that's a good point .. :-)

**Comment by ocefpaf** [comment]
@msarahan this is a perfect example where the conda solver is hurting us. The environment is solvable using conda-forge only but b/c `matplotlib` is specified and conda tries to solve for the latest, and not the most stable, we get matplotlib with the latest pinning and a bunch of packages from `defaults`, including `libgdal`. This is a place where strict channel preference would really help!

**Comment by jorisvandenbossche** [comment]
@ocefpaf I suppose that comment was meant for another issue?

**Comment by jorisvandenbossche** [comment]
ah no, I see that it is about the failing build

**Comment by jorisvandenbossche** [comment]
Amazing thing is that on Windows (on appveyor), mixing all those channels actually works ..  (https://github.com/geopandas/geopandas/pull/796)

**Comment by ocefpaf** [comment]
> Amazing thing is that on Windows (on appveyor), mixing all those channels actually works .. 

Most of the time it does not. If you are hit by this please make some noise at

https://github.com/conda/conda/issues/7626

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Re-rendering here is broken too, where is the Python matrix?

**Comment by ocefpaf** [comment]
:tada: An all `conda-forge` hacky-solution works!!!

This is actually terrible b/c we should be able to play nice and have both channels in there but I'll keep using this hack until we have a better solution.

**Pull request merged**
